- name: Uninstall Rancher
  become: true
  become_user: root
  hosts: server_nodes
  tasks:
    - name: Uninstall rke2
      ansible.builtin.shell: bash /usr/local/bin/rke2-uninstall.sh
    - name: Delete kubectl
      ansible.builtin.shell: rm /usr/local/bin/kubectl
    - name: Delete helm
      ansible.builtin.shell: rm /usr/local/bin/helm
