apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 3.5Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ nfs_server_ip | mandatory }}
    path: {{ nfs_server_path | mandatory }}
  mountOptions:
    - nfsvers=4.1