apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: plex
spec:
  capacity:
    storage: 3.5Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: <SERVER_IP>
    path: "/volume1/video"
  mountOptions:
    - nfsvers=4.1