apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: plex
  name: nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 3.5Ti
  volumeName: nfs