apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
stringData:
  mariadb-root-password: $MARIADB_ROOT_PASSWORD
  mariadb-password: $MARIADB_PASSWORD
  mariadb-replication-password: $MARIADB_REPLICATION_PASSWORD