- name: Uninstall Mariadb
  hosts: localhost
  tasks:
    - name: Remove bitnami repo
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: "https://charts.bitnami.com/bitnami"
        state: absent

    - name: Remove mariadb chart
      kubernetes.core.helm:
        name: "mariadb-{{ lookup('env', 'NAMESPACE') }}"
        release_namespace: "{{ lookup('env', 'NAMESPACE') }}"
        state: absent
        wait: true

    - name: Remove secret
      kubernetes.core.k8s:
        state: absent
        name: "mariadb-secret-{{ lookup('env', 'NAMESPACE') }}"
        api_version: v1
        kind: Secret
        namespace: "{{ lookup('env', 'NAMESPACE') }}"        

