- name: Uninstall longhorn
  become: true
  become_user: root
  hosts: first_server_node
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
  tasks:
    #Need to do this trick because I can make the ansible k8s module works and can't run the command with escaped quotes
    - name: SERVER Make a copy of rke2-config-server file
      ansible.builtin.copy:
        src: ../../resources/longhornflag.sh
        dest: longhornflag.sh
        mode: '777'

    - name: Set uninstall flag to true
      ansible.builtin.shell: sh longhornflag.sh

    - name: Delete script
      ansible.builtin.file:
        path: script.sh
        state: absent

    - name: Uninstall longhorn
      ansible.builtin.shell: helm uninstall longhorn --namespace longhorn-system

    - name: Remove longhorn repo
      ansible.builtin.shell: helm repo remove longhorn

- name: Delete longhorn config
  hosts: nodes
  become: true
  tasks:
    - name: Uninstall open-iscsi
      ansible.builtin.apt:
        name: open-iscsi
        state: absent    
        
    - name: Uninstall dm-crypt
      ansible.builtin.apt:
        name: dmsetup
        state: absent