apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: "{{ mealie_namespace | mandatory }}"
  name: mealie-bring-api
  labels:
    app: mealie-bring-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie-bring-api
  template:
    metadata:
      labels:
        app: mealie-bring-api
    spec:
      containers:
        - name: mealie-bring-api
          image: ghcr.io/felixschndr/mealie-bring-api:latest
          ports:
            - containerPort: 8742
          env:
            - name: BRING_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mealie-bring-api-secret
                  key: BRING_USERNAME
            - name: BRING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mealie-bring-api-secret
                  key: BRING_PASSWORD
            - name: BRING_LIST_NAME
              value: "{{ bring_list_name | mandatory }}"
            - name: LOG_LEVEL
              value: "DEBUG"