apiVersion: v1
kind: Service
metadata:
  name: mealie-bring-api
  namespace: "{{ mealie_namespace | mandatory }}"
spec:
  selector:
    app: mealie-bring-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8742