kind: ConfigMap
apiVersion: v1
metadata:
  name: rke2-ingress-nginx-controller
  namespace: kube-system
data:
  use-forwarded-headers: "true"
  forwarded-for-header: "X-Forwarded-For"
  #Used for seafile
  proxy-body-size: 0