- name: Setup installation
  hosts: localhost
  tasks:

  # Need to pull it because of OCI address
  - name: Pull Keycloak chart from OCI
    ansible.builtin.shell: "helm pull oci://registry-1.docker.io/bitnamicharts/keycloak --untar --untardir /tmp/"
  
  - name: Install Keycloak from pulled chart
    vars:
      keycloak_hostname: "keycloak.{{ lookup('env', 'DOMAIN_NAME') }}"
      keycloak_admin_hostname: "{{ lookup('env', 'KEYCLOAK_ADMIN_HOSTNAME') }}"
      keycloak_admin_hostname_frontend: "https://{{ lookup('env', 'KEYCLOAK_ADMIN_HOSTNAME') }}"
      hostname: "{{ lookup('env', 'DOMAIN_NAME') }}"
      keycloak_admin_user: "{{ lookup('env', 'KEYCLOAK_ADMIN_USERNAME') }}"
      keycloak_admin_password: "{{ lookup('env', 'KEYCLOAK_ADMIN_PASSWORD') }}"
    kubernetes.core.helm:
      name: "{{ lookup('env', 'NAMESPACE') }}"
      chart_ref: /tmp/keycloak/
      release_namespace: "{{ lookup('env', 'NAMESPACE') }}"
      state: present
      create_namespace: true
      values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
  
  - name: Nginx forward headers
    kubernetes.core.k8s:
      state: present
      src: configmap.yaml
