- name: Uninstall Keycloak
  hosts: localhost
  tasks:
   - name: Remove Keycloak chart
     kubernetes.core.helm:
        name: "{{ lookup('env', 'NAMESPACE') }}"
        release_namespace: "{{ lookup('env', 'NAMESPACE') }}"
        state: absent
        wait: true