- name: Setup installation
  hosts: localhost
  tasks:

    # - name: Add seafile repo
    #   kubernetes.core.helm_repository:
    #     name: seafile
    #     repo_url: "https://haiwen.github.io/seafile-helm-chart/repo"

    # Until my PR is not merged, don't pull the official repo and take the changes from my github
    - name: Clone a repo with separate git directory
      ansible.builtin.git:
        repo: 'https://github.com/Aleridia/seafile-helm-chart'
        dest: /tmp/seafile

    - name: Create the namespace
      kubernetes.core.k8s:
        name: "{{ lookup('env', 'NAMESPACE') }}"
        api_version: v1
        kind: Namespace
        state: present

- name: Install mariadb
  ansible.builtin.import_playbook: ../mariadb/install.yaml

- name: Install seafile
  hosts: localhost
  tasks:
    - name: Install chart
      vars:
        seafile_admin_password: "{{ lookup('env', 'SEAFILE_ADMIN_PASSWORD') }}"
        mysql_root_password: "{{ lookup('env', 'MARIADB_ROOT_PASSWORD') }}"
        jwt_private_key: "{{ lookup('env', 'JWT_PRIVATE_KEY') }}"
        mysql_database_password: "{{ lookup('env', 'MARIADB_PASSWORD') }}"
        ingress_url: "seafile.{{ lookup('env', 'DOMAIN_NAME') }}"
        database_user: "{{ lookup('env', 'MARIADB_USERNAME') }}"
        seafile_admin_mail: "{{ lookup('env', 'EMAIL') }}"
        nfs_server_ip: "{{ lookup('env', 'NFS_SERVER_IP') }}"
        nfs_server_path_seafile: "{{ lookup('env', 'NFS_SERVER_PATH_SEAFILE') }}"
      kubernetes.core.helm:
        name: "seafile"
        chart_ref: "/tmp/seafile/template/12.0/ce"
        release_namespace: "{{ lookup('env', 'NAMESPACE') }}"
        state: present
        values: "{{ lookup('template', 'values.yaml') | from_yaml }}"