apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  name: vaultwarden
  namespace: "{{ vaultwarden_namespace | mandatory }}"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "{{ host | mandatory }}"
      secretName: vault-warden-tls # < cert-manager will store the created certificate in this secret.
  rules:
  - host: "{{ host | mandatory }}"
    http:
      paths:
      - backend:
          service:
            name: vaultwarden
            port:
              number: 80
        path: /
        pathType: Prefix