apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: "{{ vaultwarden_namespace | mandatory }}"
spec:
  type: ClusterIP
  selector:
    app: vaultwarden
  ports:
    - port: 80
      targetPort: 80