- name: Setup config
  hosts: nodes
  become: true

  roles:
    # SSH Hardening
    - devsec.hardening.ssh_hardening
    #OS Hardening playbook
    - devsec.hardening.os_hardening
  vars:
    sysctl_overwrite:
      # Enable IPv4 traffic forwarding. Used for docker/kube
      net.ipv4.ip_forward: 1

  tasks:
    - name: Install auto-update
      become: true
      ansible.builtin.apt:
        name: unattended-upgrades
        update_cache: yes
        state: latest
    - name: Configure auto-update
      become: true
      ansible.builtin.copy:
        src: resources/20auto-upgrades
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        owner: root
        group: root
        mode: '0644'